ATIVIDADE 1 


SELECT NAME 
FROM CITY 
WHERE COUNTRYCODE = 'USA' AND POPULATION > '120000';


ATIVIDADE 2 

SELECT * FROM CITY;

ATIVIDADE 3 

SELECT * FROM CITY
WHERE ID = '1661';

ATIVIDADE 4 

SELECT * FROM CITY
WHERE POPULATION > '100000'
AND COUNTRYCODE =  'USA';

ATIVIDADE 5

SELECT CITY, STATE FROM STATION; 

ATIVIDADE 6  --Average Population of Each Continent

SELECT CONTINENT, FLOOR (AVG(CITY.POPULATION))
FROM CITY 
INNER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE;
GROUP BY CONTINENT;


ATIVIDADE 7

SELECT * FROM CITY 
WHERE COUNTRYCODE = 'JPN';

ATIVIDADE 8

SELECT CITY.NAME
FROM CITY 
INNER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE
WHERE CONTINENT = 'Africa';


ATIVIDADE 9

SELECT SUM(CITY.POPULATION)
FROM CITY 
INNER JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.CODE 
WHERE CONTINENT = 'Asia';

ATIVIDADE 10

 SELECT CITY,STATE FROM STATION;

ATIVIDADE 11

SELECT DISTINCT CITY FROM STATION 
WHERE MOD(ID,2) = 0;

ATIVIDADE 12

SELECT NAME FROM Employee
WHERE salary > '2000' AND months < '10';

ATIVIDADE 13

SELECT NAME 
FROM Employee
ORDER BY NAME;

ATIVIDADE 14

SELECT Name
FROM STUDENTS
WHERE Marks > '75'
ORDER By SUBSTRING(Name,-3,LENGTH(Name)),ID;

ATIVIDADE 15

SELECT COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION;

ATIVIDADE 16

SELECT CITY, LENGTH(CITY) 
FROM STATION 
WHERE LENGTH(CITY) IN(
SELECT MAX(LENGTH(CITY))
FROM STATION 
UNION
SELECT MIN(LENGTH(CITY))
FROM STATION
)
ORDER BY LENGTH(CITY) DESC, CITY ASC LIMIT 2;

ATIVIDADE 17

SELECT DISTINCT CITY
FROM STATION 
WHERE CITY 
LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'o%' OR CITY LIKE 'u%';

ATIVIDADE 18
ATIVIDADE 19
ATIVIDADE 20
ATIVIDADE 21
ATIVIDADE 22
ATIVIDADE 23
ATIVIDADE 24